version: "3.6"

services:
  vault:
    image: vault:latest
    cap_add:
      - IPC_LOCK
    command: 'server -config /vault/config'
    networks:
      - proxy
      - backend
    secrets:
      - source: vault_config
        target: /vault/config/vault_config.hcl
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8200"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:vault.chaos.sh"

  mysql:
    image: mysql:5.7.24
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=vault
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_DATABASE=vault
    networks:
      - backend
    secrets:
      - mysql_user_password
    volumes:
      - mysql:/var/lib/mysql

networks:
  proxy:
    external: true
  backend:

secrets:
  vault_config:
    name: m3philis_chaos_vault_config
  mysql_user_password:
    name: m3philis_chaos_vault_mysql_password

volumes:
  mysql:
