version: "3.6"

services:
  nextcloud:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:own.m3philis.com"

networks:
  proxy:
    external: true

volumes:
  nextcloud:
