---

- name: install dependencies
  apt:
    cache_valid_time: 3600
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: import repo PGP key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0EBFCD88

- name: import repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present
    validate_certs: yes

- name: install binary
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce

- name: ensure host volume folder is present
  file: path=/data state=directory
