version: "3.6"

services:
  proxy:
    image: traefik:1.7
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/traefik.toml:/traefik.toml
      - /data/traefik/acme.json:/acme.json
    networks:
      - proxy
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:traefik.gnomus.systems"

networks:
  proxy:
    external: true
