version: '3.6'

services:
  murmur:
    image: goofball222/murmur
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - cert:/opt/murmur/cert
      - config:/opt/murmur/config
      - data:/opt/murmur/data
      - log:/opt/murmur/log
    environment:
      - TZ=UTC

volumes:
  cert:
  config:
  data:
  log:
